// app/angular/src/app/app.component.ts
import { Component } from '@angular/core';

import { DomSanitizer } from '@angular/platform-browser';

@Component({
  selector: '#angular-app',
  // templateUrl: './app.component.html',
  template:require('./app.component.html'),
  // styleUrls: ['./app.component.less'],
})
export class AppComponent {
  name='Micro-Angular';
  logo=require('@common/images/angular.svg');
  constructor( private sanitizer: DomSanitizer ) {}
}

<div style="text-align: center;">
  <h1>{{name}}</h1>
  <img style="max-width: 300px;" [src]="sanitizer.bypassSecurityTrustResourceUrl(logo)" />
</div>

// app/vue/app.jsx
const App={
  data(){
    return{
      name:'Micro-Vue',
      logo:require('@common/images/vue.png'),
    };
  },
  render(h){
    return <div id="vue-app">
      <div style="text-align:center;">
        <h1>{this.name}</h1>
        <div style="padding:20px"><img style="max-width:260px;" src={this.logo} /></div>
      </div>
    </div>;
  },
};

export default App;
